affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./encoder_kan_smaller_DELETE
device: cuda
grid: 8
grid_eps: 0.02
grid_range:
- -1
- 1
k: 5
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 14
symbolic.funs_name.0:
- - '0'
  - exp
  - exp
  - '0'
  - x
  - x
  - '0'
  - x
  - x
- - '0'
  - '0'
  - x
  - '0'
  - x
  - x
  - '0'
  - x
  - x
- - '0'
  - '0'
  - exp
  - '0'
  - x
  - x
  - '0'
  - x
  - x
- - '0'
  - '0'
  - x
  - '0'
  - x
  - x
  - '0'
  - x
  - x
- - '0'
  - '0'
  - exp
  - '0'
  - x
  - x
  - '0'
  - x
  - x
symbolic.funs_name.1:
- - sin
  - '0'
  - cos
  - '0'
  - 1/x
- - sin
  - '0'
  - cos
  - '0'
  - sin
- - tan
  - '0'
  - sin
  - '0'
  - '0'
- - x^2
  - 1/x
  - cos
  - cos
  - x
- - '0'
  - '0'
  - x^2
  - '0'
  - '0'
symbolic_enabled: true
width:
- - 9
  - 0
- - 5
  - 0
- - 5
  - 0
